apiVersion: v1 
kind: pod   
metadata: 
  name: my-app  
  namespace: project-cool   
spec:  
  containers:  
  - name: first-container  
    image: nginx:latest 
    resources: 
      limits:                     
         memory: "128Mi"  
         cpu: "500m" 
    ports:  
      - containerPort: 80   

